language: go

before_install:
  - make dev

  - curl -L https://github.com/coreos/etcd/releases/download/v3.3.8/etcd-v3.3.8-linux-amd64.tar.gz -o etcd-v3.3.8-linux-amd64.tar.gz
  - tar xzf etcd-v3.3.8-linux-amd64.tar.gz
  - sudo mv etcd-v3.3.8-linux-amd64/etcd /bin/
  - sudo mv etcd-v3.3.8-linux-amd64/etcdctl /bin/
  - etcd &

go:
  - 1.10.x
  - tip

before_script:
  - make lint

script:
  - make test
